# Generated by Django 3.2.25 on 2025-09-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250929_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='ujser',
            new_name='user',
        ),
    ]
